Add -pthread to C++ compiler flags
Summary:
Ref: https://github.com/facebook/Surround360/issues/3

`undefined reference to symbol 'pthread_create@GLIBC_2.2.5'` when compiling rendering software.

We explicitly add `pthread` to make sure it's used. clang doesn't use this argument, so we only apply it if not `APPLE`

No need to use `PLATFORM_SPECIFIC_LIBS`.

Differential Revision: D3625661

fbshipit-source-id: c95df0c41cfdb1482fd4ec30e0e0327158f4923a