set the required standard to C++14
Summary:
To avoid compilation errors such as

  error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?

Reviewed By: tschrager

Differential Revision: D8757706

fbshipit-source-id: 96dc359fa88f5059be972afb5b7c3e1a00701842